set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_PROVIDED_FORTRAN ON)

get_filename_component(WHEREABOUTS_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
cmake_path(GET WHEREABOUTS_SOURCE_ROOT ROOT_NAME WHEREABOUTS_SOURCE_DRIVE)
set(WHEREABOUTS_REPRO_FLAGS
    "/experimental:deterministic /pathmap:${WHEREABOUTS_SOURCE_DRIVE}=.")
set(VCPKG_C_FLAGS "${WHEREABOUTS_REPRO_FLAGS}")
set(VCPKG_CXX_FLAGS "${WHEREABOUTS_REPRO_FLAGS}")
